### PR TITLE
Bundle naming fixes

### LINKED ISSUE #1157: clash of impl names in rec bundles (disambiguators are no longer valid)
impls coming from different modules in a recursive bundles don't get a new disambiguator so the names can clash.

### LINKED ISSUE #1200: Stable name for rec bundles
Rec bundles have names that contain a hash. This is problematic because if the content of the bundle changes the name of the generated file also changes which makes it hard to manage projects. We should instead generate a name using the names of the modules that compose the bundle, with a disambiguation only if needed.

### PR DESCRIPTION
**Pull request by maximebuyse**
This PR:
- Closes #1200. Makes bundle names stable, by computing the hash based on the names of the modules going inside the bundle (instead of the items)
- Fixes #1157. By adding a disambiguator when names clash, instead of modifying the last string in the path (which fails for impls that don't have a string at the en of their paths)

### CODE REVIEW

File: engine/lib/concrete_ident/concrete_ident.ml [hunk 1]
```diff
@@ -635,6 +634,14 @@ module Create = struct
   let constructor name =
     let path = name.def_id.path @ [ { data = Ctor; disambiguator = 0 } ] in
     { name with def_id = { name.def_id with path } }
+
+  let add_disambiguator name disambiguator =
+    let path = name.def_id.path in
+    let last = List.last_exn path in
+    let path =
+      List.drop_last_exn path @ [ { data = last.data; disambiguator } ]
```
Comment (karthikbhargavan) [inline engine/lib/concrete_ident/concrete_ident.ml:642]: Shopuld we be using an "_exn" function here? If needed, let's put a comment saying why this cannot fail.

**Review by karthikbhargavan — COMMENTED** [review]
Generally looks good, but two comments, since we are touching this code anyway.

First, can we rename "Rec_bundle" to "Cyclic_bundle"? This would be more precise.
Second, could we list the files that are part of the bundle in the top of the file somehow?

I can imagine the second ask to be harder.

**Comment by maximebuyse** [comment]
libcrux CI job: https://github.com/cryspen/libcrux/actions/runs/12480998112/job/34832756469

File: engine/lib/concrete_ident/concrete_ident.ml (hunk 1 above)
Comment (maximebuyse) [reply engine/lib/concrete_ident/concrete_ident.ml]: Done

**Comment by maximebuyse** [comment]
> Generally looks good, but two comments, since we are touching this code anyway.
> 
> First, can we rename "Rec_bundle" to "Cyclic_bundle"? This would be more precise. Second, could we list the files that are part of the bundle in the top of the file somehow?
> 
> I can imagine the second ask to be harder.

Done for the first one. The list of files (or maybe modules) is a good idea, but let's leave it for later. I think trying to name the bundle with a name containing the names of the modules it contains (which is part of the naming refactor) would already help.

**Review by karthikbhargavan — APPROVED** [review]
Looks good, let's merge if libcrux CI passes.
