### PR TITLE
fix(backend) Filter Impl after adding comments.

### LINKED ISSUE #1202: Interface only mode still produces an fst file if there are errors
With the following rust code: 
```
fn bad<'a>(x: (& 'a mut i32, & 'a mut i32)) -> & 'a mut i32 {
    x.0
}

fn ok() {}
```

Extracting with `cargo hax into -i '+:**' fstar --interfaces '+!**'` produces an fst file and an fsti. The fsti contains:
```
val ok: Prims.unit -> Prims.Pure Prims.unit Prims.l_True (fun _ -> Prims.l_True)
(* item error backend: (DirectAndMut) The mutation of this [1m&mut[0m is not allowed here.
...
*)
```
and the fsti only contains a comment about the error.
This is annoying because F* will complain that `ok` is not implemented in the fst file. It would be better to produce no fst file in this case.

### PR DESCRIPTION
**Pull request by maximebuyse**
Fixes #1202.

This avoids creating an fst file with only comments in it in fsti-only mode. The filtering of `Impl` elements is moved to after treating comments.

### CODE REVIEW

File: engine/backends/fstar/fstar_backend.ml [hunk 1]
```diff
@@ -1618,6 +1617,7 @@ let strings_of_item (bo : BackendOptions.t) m items (item : item) :
            let s = "(* " ^ s ^ " *)" in
            if interface_mode then [ (`Impl s, `Newline); (`Intf s, `Newline) ]
            else [ (`Impl s, `Newline) ])
+  |> List.filter ~f:(function `Impl _, _ when no_impl -> false | _ -> true)
```
Comment (karthikbhargavan) [inline engine/backends/fstar/fstar_backend.ml:1620]: Yes, this change looks right, but we need some tests.

**Review by karthikbhargavan — APPROVED** [review]
Can we add some tests?

**Comment by maximebuyse** [comment]
> Can we add some tests?

Done

**Comment by maximebuyse** [comment]
> > Can we add some tests?
> 
> Done

Actually the test I added breaks the CI because it tests the running hax on unsupported rust code (where hax produces a result but with an exit code of 1). I think we should merge anyway, but it would be nice to be able to test what happens with unsupported code. I'll add a comment in #485
