### PR TITLE
Fix question marks

### LINKED ISSUE #399: Fix monadic transform for `?`s
- [ ] Add tests
 - [ ] F*

### PR DESCRIPTION
**Pull request by W95Psp**
This PR fixes #399 and adds some more tests.

### CODE REVIEW

File: tests/side-effects/src/lib.rs [hunk 1]
```diff
@@ -1,47 +1,47 @@
 #![allow(dead_code)]
 fn add3(x: u32, y: u32, z: u32) -> u32 {
-    x + y + z
+    x.wrapping_add(y).wrapping_add(z)
```
Comment (franziskuskiefer) [inline tests/side-effects/src/lib.rs:3]: How are these changes related to the PR?
While you're here, add comments what these tests are doing.

**Review by franziskuskiefer — CHANGES_REQUESTED** [review]
Thanks, generally looks good to me.
But lets start documenting things. Please comment all the code you're touching.

File: tests/side-effects/src/lib.rs (hunk 1 above)
Comment (W95Psp) [reply tests/side-effects/src/lib.rs:5]: I change everything from `+` to `wrapping_add` so that I make sure (locally) that things are typechecking in F*, without bothering to add preconditions everywhere so that the addition doesn't overflow!

I want at some point to make our "unit" tests to be typed-checked in the backends at CI, but for now there is no such infrastructure :(

I added comments!

**Review by franziskuskiefer — APPROVED** [review]
Thanks!
