### PR TITLE
Engine: get rid of most of exception throwing function calls, improve parsers and error reports

### LINKED ISSUE #1187: F* Backend: catch Failure and print readable error message
The F* backend has a number of calls to "failwith" notably when parsing things as F* but also in other expected things.
These result in the the hax invocation failing with a long and somewhat unreadable backtrace with no indication of the "span" in which this error was triggered. We should systematically catch these "Failure" exceptions in the backend and print nicer messages with the span of the source code.

### PR DESCRIPTION
**Pull request by W95Psp**
This PR:
 - adds a version to `haxmeta` files
 - adds a version to the engine
 - makes the frontend check haxmeta versions
 - makes the engine check the frontend version
 - improve parsing error reporting
 - makes generated parsers conform to yojson style
 - report parsing errors in the F* backend
 - removes most of `*_exn` calls
 - removes most of failwith calls

Fixes https://github.com/hacspec/hax/issues/1150, fixes https://github.com/hacspec/hax/issues/1188, fixes #1187

Context: this PR goes toward better user experience for releasing hax v0.1, it gets rid of most of remaining unhandled explicit failures

### CODE REVIEW

**Review by maximebuyse — APPROVED** [review]
Great :tada:

File: engine/lib/attr_payloads.ml [hunk 1]
```diff
@@ -6,7 +6,18 @@ let payloads : attrs -> (Types.ha_payload * span) list =
...
     (* we have to parse ["JSON"]: first a string, then a ha_payload *)
     function
-    | `String s -> Yojson.Safe.from_string s |> Types.parse_ha_payload
+    | `String s -> (
+        match Yojson.Safe.from_string s |> Types.safe_ha_payload_of_yojson with
+        | Error _ ->
+            Stdlib.prerr_endline
+              [%string
+                {|
+The hax engine could not parse a hax attribute.
```
Comment (karthikbhargavan) [inline engine/lib/attr_payloads.ml:15]: Couldn't this also happen if the hax_lib is right but somehow the content of the attibute is malformed?

Comment (W95Psp) [reply engine/lib/attr_payloads.ml:15]: No, this situation should never happen, the hax lib attributes are always JSON serializations of a Rust enum, and the OCaml parser used here is directly generated from the Rust enum definition.

So, we could still have a bug in generated parsers, but this almost never happened (it happened once because of OCaml ints being smaller than Rust ints)

**Review by karthikbhargavan — APPROVED** [review]
Looks great. Did you try on libcrux? If not, I can tomorrow.

**Comment by W95Psp** [comment]
The job is successful, I'm mergining
