### PR TITLE
fix(engine) Make sub-parts of `Quote` visited by visitors

### LINKED ISSUE #1196: No rewriting of `$` names in `fstar!` macro with bundling
```rust
mod a {
    #[hax_lib::requires(fstar!("$super::b::cond()"))]
    pub fn f(){super::b::g()}
}
mod b {
    pub fn g(){super::a::f()}
    pub fn cond() -> bool {true}
}

```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/a598467a5d/gist=fb5e07a4021ac7e68906a67472630599)

The example above has the following code in its fstar bundle: 
```
let cond (_: Prims.unit) : bool = true

let rec f (_: Prims.unit)
    : Prims.Pure Prims.unit
      (requires Playground.B.cond ())
      (fun _ -> Prims.l_True) = g ()
```

Here we find `Playground.B.cond` in the precondition which should be transformed to just `cond` to avoid a cyclic dependency. I suspect the macro does something at the string level which will make it hard to fix.

### PR DESCRIPTION
**Pull request by maximebuyse**
Fixes #1196 

The investigation for #1196 revealed that subparts of `Quote` variant in the AST were ignored by visitors. The easiest way to change that is to use a `quote_contents` ADT inside instead of an inlined polymorphic variants. This involves quite a few changes here and there.

### CODE REVIEW

**Comment by maximebuyse** [comment]
I succeeded in making a version that fixes the bug for F*. But I am not sure that it does the right thing for the generic printer (at least it builds correctly and doesn't break tests).

File: engine/backends/coq/coq/coq_backend.ml [hunk 1]
```diff
@@ -151,6 +151,16 @@ struct
       method borrow_kind_Unique = default_document_for "borrow_kind_Unique"
       method common_array x1 = brackets (separate (semi ^^ space) x1)
 
+      method quote_content_Verbatim _v =
```
Comment (karthikbhargavan) [inline engine/backends/coq/coq/coq_backend.ml:154]: This may need a review from @cmester0

File: engine/backends/fstar/fstar_backend.ml [hunk 2]
```diff
@@ -692,10 +692,10 @@ struct
...
     List.map
       ~f:(function
-        | `Verbatim code -> code
-        | `Expr e -> pexpr e |> term_to_string
-        | `Pat p -> ppat p |> pat_to_string
-        | `Typ p -> pty span p |> term_to_string)
+        | Verbatim code -> code
+        | Expr e -> pexpr e |> term_to_string
+        | Pattern p -> ppat p |> pat_to_string
+        | Typ p -> pty span p |> term_to_string)
```
Comment (karthikbhargavan) [inline engine/backends/fstar/fstar_backend.ml:698]: Generally, the use of explicit constructors is better so this change seem fine, unless we were relying on subtyping or on one of these constructor names also being used in another type. As long as the code compiles and typechecks this should not be the case.

File: engine/lib/generic_printer/generic_printer.ml [hunk 3]
```diff
@@ -231,14 +231,15 @@ module Make (F : Features.T) = struct
       [local] is true, otherwise it prints the full path, separated by
       `module_path_separator`. *)
 
-      method quote (quote : quote) : document =
+      method quote ~contents ~witness:_ : document =
```
Comment (karthikbhargavan) [inline engine/lib/generic_printer/generic_printer.ml:234]: why not take an argument of type `quote` here, which has both the contents and witness?

File: engine/lib/generic_printer/generic_printer_template.ml [hunk 4]
```diff
@@ -35,6 +35,11 @@ struct
       method borrow_kind_Mut _x1 = default_document_for "borrow_kind_Mut"
       method borrow_kind_Shared = default_document_for "borrow_kind_Shared"
       method borrow_kind_Unique = default_document_for "borrow_kind_Unique"
+      method cf_kind_BreakOnly = default_document_for "cf_kind_BreakOnly"
+
+      method cf_kind_BreakOrReturn =
+        default_document_for "cf_kind_BreakOrReturn"
+
```
Comment (karthikbhargavan) [inline engine/lib/generic_printer/generic_printer_template.ml:42]: Is this a drive-by fix, how is it related to Quote?

File: engine/lib/phases/phase_transform_hax_lib_inline.ml [hunk 5]
```diff
@@ -134,33 +133,22 @@ module%inlined_contents Make (F : Features.T) = struct
...
           let verbatim = split_str ~on:"SPLIT_QUOTE" str in
           let contents =
-            let rec f verbatim
-                (code :
-                  [ `Verbatim of string
-                  | `Expr of B.expr
-                  | `Pat of B.pat
-                  | `Typ of B.ty ]
-                  list) =
+            let rec f verbatim (code : B.quote_content list) =
```
Comment (karthikbhargavan) [inline engine/lib/phases/phase_transform_hax_lib_inline.ml:141]: Here, your code looks nicer than what was there before.

File: test-harness/src/snapshots/toolchain__loops into-fstar.snap [hunk 6]
```diff
@@ -651,7 +651,7 @@ let enumerated_chunked_slice (#v_T: Type0) (slice: t_Slice v_T) : u64 =
     (fun count i ->
         let count:u64 = count in
         let i:usize = i in
-        i <= Core.Slice.impl__len #v_T slice)
+        i <= Core.Slice.impl__len #v_T slice <: usize)
```
Comment (karthikbhargavan) [inline test-harness/src/snapshots/toolchain__loops into-fstar.snap:654]: This diff seems strange, but not wrong?

**Review by karthikbhargavan — APPROVED** [review]
Generally, this looks good to me. Let's test on libcrux, and maybe you can resolve some of my comments.

File: engine/lib/generic_printer/generic_printer_template.ml (hunk 4 above)
Comment (maximebuyse) [reply engine/lib/generic_printer/generic_printer_template.ml:42]: This is generated code. I used the tool to regenerate this and this was part of it. This is because we changed the AST as part of https://github.com/hacspec/hax/pull/988, and this file hasn't been regenerated since.

File: engine/lib/generic_printer/generic_printer.ml (hunk 3 above)
Comment (maximebuyse) [reply engine/lib/generic_printer/generic_printer.ml:234]: My understanding is that the method signature is generated from the AST so we don't get to choose. But maybe I am wrong and there is a better way. @W95Psp will know.

File: test-harness/src/snapshots/toolchain__loops into-fstar.snap (hunk 6 above)
Comment (W95Psp) [reply test-harness/src/snapshots/toolchain__loops into-fstar.snap:654]: I think that makes sense: https://github.com/hacspec/hax/blob/f47b2ae440333850f9990c59f7200e79802b64f5/tests/loops/src/lib.rs#L26 introduces a quote.
The contents of the quote were previously not visited by any visitor, now they are, and the subtyping insertion is from a visitor.

File: engine/backends/coq/coq/coq_backend.ml [hunk 7]
```diff
@@ -151,6 +151,16 @@ struct
...
+        default_document_for "quote_content_Verbatim"
+
+      method quote_content_Expr _e = default_document_for "quote_content_Expr"
+
+      method quote_content_Pattern _p =
+        default_document_for "quote_content_Pattern"
+
+      method quote_content_Typ _t = default_document_for "quote_content_Typ"
+
```
Comment (W95Psp) [inline engine/backends/coq/coq/coq_backend.ml:163]: Those methods should be defined in `generic_printer` I think, with good defaults:
 - verbatim just prints the string verbatim
 - `quote_content_* value` should be `value#p`

File: engine/lib/generic_printer/generic_printer.ml [hunk 8]
```diff
@@ -231,14 +231,15 @@ module Make (F : Features.T) = struct
...
-            | `Expr e -> self#print_expr AstPosition_Quote e
-            | `Pat p -> self#print_pat AstPosition_Quote p
-            | `Typ p -> self#print_ty AstPosition_Quote p)
-          quote.contents
+          ~f:(fun doc ->
+            match doc#v with
+            | Verbatim code -> string code
+            | Expr e -> self#print_expr AstPosition_Quote e
+            | Pattern p -> self#print_pat AstPosition_Quote p
+            | Typ t -> self#print_ty AstPosition_Quote t)
```
Comment (W95Psp) [inline engine/lib/generic_printer/generic_printer.ml:241]: Here, we should directly use `doc#p`: this will call into the underlying methods `self#quote_content_{Verbatim,Expr,Pattern,Typ}`

File: engine/lib/generic_printer/generic_printer_template.ml [hunk 9]
```diff
@@ -318,6 +319,16 @@ struct
...
+      method quote_content_Expr _x1 = default_document_for "quote_content_Expr"
+
+      method quote_content_Pattern _x1 =
+        default_document_for "quote_content_Pattern"
+
+      method quote_content_Typ _x1 = default_document_for "quote_content_Typ"
+
+      method quote_content_Verbatim _x1 =
+        default_document_for "quote_content_Verbatim"
+
```
Comment (W95Psp) [inline engine/lib/generic_printer/generic_printer_template.ml:331]: Related to my [other comment in `coq/coq_backend.ml`](https://github.com/hacspec/hax/pull/1206/files#r1903775169):

Those will disappear after implementing default methods in generic_printer.ml, don't forget to regenerate at that point!

File: engine/backends/coq/coq/coq_backend.ml (hunk 1 above)
Comment (maximebuyse) [reply engine/backends/coq/coq/coq_backend.ml]: This is gone now that we have default methods for this.

**Comment by maximebuyse** [comment]
> Thanks, there's a few things to change, but that looks good :)

Thanks, everything should be good now!

**Review by W95Psp — APPROVED** [review]
LGTM, let's merge!
